port: "9104"
mysql:
  host: "db-mysql:3306"
  database: "dbo_db"
  username: "root"
  password: "4kdatxchdnxr8zs"
  max_idle_conns: 10
  max_open_conns: 10
  conn_max_lifetime: "3s"
  conn_max_idletime: "2s"
jwt:
  signing_key: "bq6M68YCXnv2iltpH3h6dz51xn2Uv3dh"
  exp: "24h"
