version: '3'
services:
  app:
    build:
      context: .
    restart: on-failure
    ports:
      - "9104:9104"
    volumes:
      - ./config.yaml:/app/config.yaml
    depends_on:
      - database
    command: >
      bash -c "./main serve"
    networks:
      - my_project_network

  database:
    image: mysql:latest
    container_name: "db-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: "4kdatxchdnxr8zs"
      MYSQL_DATABASE: "dbo_db"
    ports:
      - "3306:3306"
    networks:
      - my_project_network

  migration:
    build:
      context: .
    depends_on:
      - database
    command: >
      bash -c "until (echo > /dev/tcp/database/3306) &> /dev/null; do echo 'Waiting for the database to be ready...'; sleep 1; done && ./main migrate && exit 0"
    networks:
      - my_project_network

networks:
  my_project_network:
    driver: bridge
